smutel/terraform-provider-netbox

netbox/data_netbox_ipam_vlan.go
=> fix: Data netbox_ipam_vlan return code 400

.github/workflows/master.yml, .github/workflows/release.yml, .goreleaser.yml, README.md, package.json, utils/getChangelogRelease
=> Improve release process

netbox/resource_netbox_ipam_ip_addresses.go
=> IP address not updating when dns_name removed

.github/ISSUE_TEMPLATE/feature.md, .github/auto_assign.yml, .github/workflows/pr.yml
Use github-actions [conventional-pr](https://github.com/Namchee/conventional-pr) to check commits format.
=> ci: Add conventional check in CI

docs/resources/ipam_ip_addresses.md, docs/resources/tenancy_tenant.md, docs/resources/virtualization_vm.md, netbox/resource_netbox_ipam_ip_addresses.go, netbox/resource_netbox_tenancy_tenant.go, netbox/resource_netbox_virtualization_vm.go, netbox/util.go
=> feat: Add custom_fields to IP address resource

docs/resources/ipam_vlan.md, examples/main.tf, netbox/resource_netbox_ipam_vlan.go
=> feat: Add custom_fields to vlan resource

README.md, docs/data-sources/ipam_aggregate.md, docs/resources/ipam_aggregate.md, examples/main.tf, netbox/data_netbox_ipam_aggregate.go, netbox/provider.go, netbox/resource_netbox_ipam_aggregate.go
=> feat: Add resource and data for IPAM aggregate

netbox/util.go
Fixes https://github.com/smutel/terraform-provider-netbox/issues/32
=> fix: Workaround for weird terraform behavior to fix boolean custom_fields

.github/workflows/master.yml, .github/workflows/pr.yml, .github/workflows/release.yml, docs/data-sources/ipam_service.md, docs/resources/ipam_service.md, examples/.terraform.lock.hcl, examples/main.tf, examples/netbox_docker_variables.sh, netbox/data_netbox_ipam_service.go, netbox/provider.go, netbox/resource_netbox_ipam_service.go
=> feat: Add resource and data for IPAM service

netbox/resource_netbox_ipam_ip_addresses.go
=> feat: Change ValidateFunc for ipam_ip_addresses to allow IPv6

CHANGELOG.md
=> chore(release): 1.3.0

.github/workflows/release.yml
Fix https://github.com/smutel/terraform-provider-netbox/actions/runs/1268946236
=> fix: Fix CI for release generation

docs/data-sources/tenancy_tenant_group.md, docs/index.md, docs/resources/ipam_ip_addresses.md, netbox/resource_netbox_ipam_ip_addresses.go
=> fix: Terraform crashes when ip address not affected to vm/device

CHANGELOG.md, package.json
=> chore(release): 2.0.2

.gitignore, examples/main.tf
* Set vcpus in vm test creation
* package.json not updated by standard-version
=> ci: Fix ci changelog

netbox/data_netbox_ipam_ip_addresses.go
=> fix: Allow ipv6 addresses for data.netbox_ipam_ip_addresses

go.mod, go.sum, vendor/github.com/smutel/go-netbox/netbox/models/v_l_a_n_group.go, vendor/modules.txt
=> fix: JSON error when vlangroup contains scope

.vscode/launch.json, README.md, examples/resources/netbox_ipam_ip_addresses/resource.tf, main.go
Fixes #133
This adds a debug mode to the provider.
I'm not sure how to handle IDE configs for debugging. Do you want to add them to  the repository or .gitignore?
=> feat: Add debug option to main()

examples/main.tf, examples/resources/netbox_ipam_ip_range/resource.tf, examples/resources/netbox_ipam_prefix/resource.tf, examples/resources/netbox_ipam_vlan/resource.tf, netbox/provider.go, netbox/resource_netbox_ipam_ip_range.go
Fixes: #141 
This adds an ip_range resource to this provider. This is mostly a copy, paste and replace from ipam_prefix resource.
=> feat: Add IP Range resource type

netbox/extras/resource_netbox_extras_custom_field.go, netbox/extras/resource_netbox_extras_custom_field_boolean_test.go, netbox/extras/resource_netbox_extras_custom_field_date_test.go, netbox/extras/resource_netbox_extras_custom_field_integer_test.go, netbox/extras/resource_netbox_extras_custom_field_json_test.go, netbox/extras/resource_netbox_extras_custom_field_longtext_test.go, netbox/extras/resource_netbox_extras_custom_field_multiobject_test.go, netbox/extras/resource_netbox_extras_custom_field_multiselect_test.go, netbox/extras/resource_netbox_extras_custom_field_object_test.go, netbox/extras/resource_netbox_extras_custom_field_select_test.go, netbox/extras/resource_netbox_extras_custom_field_text_test.go, netbox/extras/resource_netbox_extras_custom_field_url_test.go, netbox/internal/customfield/customfield.go
=> feat: Custom field tests

netbox/internal/util/util.go
=> Wrong conversion of filter name with underscore

netbox/provider.go
=> fix: Provider is crashing when insecure=true
